    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Входящие" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Входящие</cufontext></cufon>
		<cufon class="cufon cufon-canvas" alt="сообщения" style="width: 62px; height: 24px;"><canvas width="108" height="32" style="width: 108px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>сообщения</cufontext></cufon>
	    </h2>
	    <?php include (APPLICATION_PATH . 'views/paginator.phtml'); ?>
	    <div class="clr"></div>
	</div>
    </div>
