	</div>
	<div class="footer">
	    <div class="footer_resize">
		<p class="lf">&copy; Copyright <a href="#">NCC RealEstate</a>.</p>
		<!--ul class="fmenu">
		    <li><a href="index.html">Home</a></li>
		    <li><a href="support.html">Support</a></li>
		    <li class="active"><a href="blog.html">Blog</a></li>
		    <li><a href="about.html">About Us</a></li>
		    <li><a href="contact.html">Contacts</a></li>
		</ul-->
		<div class="clr"></div>
	    </div>
	</div>
    </div>
</body>
</html>
