<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <!-- Main Stylesheet --> 
    <link href="/public/css/style.css" media="screen" rel="stylesheet" type="text/css" >
    <!-- CuFon: Enables smooth pretty custom font rendering. 100% SEO friendly. To disable, remove this section -->
    <script type="text/javascript" src="/public/js/cufon-yui.js"></script>
    <script type="text/javascript" src="/public/js/arial.js"></script>
    <script type="text/javascript" src="/public/js/cuf_run.js"></script>
    <!-- CuFon ends -->
</head>
<body>
    <div class="main">
	<div class="header">
	    <div class="header_resize">
		<div class="logo"><h1><a href="/">
			    <span><cufon class="cufon cufon-canvas" alt="ERPCRealEstate" style="width: 81px; height: 32px;"><canvas width="140" height="45" style="width: 140px; height: 45px; top: -7px; left: -20px;"></canvas><cufontext>ERPCRealEstate</cufontext></cufon></span>
			    <cufon class="cufon cufon-canvas" alt=" " style="width: 8px; height: 32px;"><canvas width="78" height="43" style="width: 78px; height: 43px; top: -7px; left: -21px;"></canvas><cufontext> </cufontext></cufon>
			    <cufon class="cufon cufon-canvas" alt="Company " style="width: 132px; height: 32px;"><canvas width="202" height="43" style="width: 202px; height: 43px; top: -7px; left: -21px;"></canvas><cufontext>Company </cufontext></cufon>
			    <small>
				<cufon class="cufon cufon-canvas" alt="Put " style="width: 30px; height: 16px;"><canvas width="64" height="22" style="width: 64px; height: 22px; top: -3px; left: -11px;"></canvas><cufontext>Put</cufontext></cufon>
				<cufon class="cufon cufon-canvas" alt="your " style="width: 37px; height: 16px;"><canvas width="72" height="22" style="width: 72px; height: 22px; top: -3px; left: -11px;"></canvas><cufontext>your</cufontext></cufon>
				<cufon class="cufon cufon-canvas" alt="best " style="width: 36px; height: 16px;"><canvas width="71" height="22" style="width: 71px; height: 22px; top: -3px; left: -11px;"></canvas><cufontext>best</cufontext></cufon>
				<cufon class="cufon cufon-canvas" alt="slogan " style="width: 54px; height: 16px;"><canvas width="88" height="22" style="width: 88px; height: 22px; top: -3px; left: -11px;"></canvas><cufontext>slogan</cufontext></cufon>
				<cufon class="cufon cufon-canvas" alt="here" style="width: 34px; height: 16px;"><canvas width="63" height="22" style="width: 63px; height: 22px; top: -3px; left: -11px;"></canvas><cufontext>here</cufontext></cufon>
			    </small></a></h1>
		</div>
		<?php if ($this->registry->user) include (APPLICATION_PATH . 'views/menu.phtml'); ?>
		<div class="clr"></div>
	    </div>
	</div>
	<div class="block">