
    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Договора" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Договора</cufontext></cufon>
	    </h2>

	    <div class="clr"></div>
	    <?php echo $user;?>
	</div>
    </div>
    <br />
    <br />
    <div class="clr"></div>
    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Платежи" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Платежи</cufontext></cufon>
	    </h2>
	    <div class="clr"></div>
	</div>
    </div>