    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Договора" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Договора</cufontext></cufon>
	    </h2>
	    <?php foreach ($agreements as $item) :?>
	    <table class="index" width="100%">
		<thead
		    <tr>
			<th colspan="6">
			    Договор <?php echo ($item->getAgreement_Type()==1) ? 'Инвестирования' : 'Бронирования';?>
			    #<?php echo $item->getNo_();?>
			</th>
		    </tr>
		</thead>
		<tbody>
		    <tr>
			<th>Описание:</th><td colspan="5"><?php echo $item->getDescription();?></td>
		    </tr>
		    <tr>
			<th width="100">Дата договора:</th><td width="200"><?php echo date_format($item->getAgreement_Date(), 'd/m/Y') ?></td>
			<th width="100">Код очереди:</th><td width="160"><?php echo $item->getBuilding_Turn_Code(); ?></td>
			<th width="100">Сумма договора:</th><td width="160"><?php echo number_format($item->getAgreement_Amount(), 2, '.', ' '); ?></td>
		    </tr>
		    <tr>
			<th>№ договора:</th><td><?php echo $item->getAgreementNo();?></td>
			<th>Номер дома:</th><td><?php echo $item->getHouse_Code(); ?></td>
			<th>Оплачено:</th><td><?php echo number_format($item->getPayed(), 2, '.', ' '); ?></td>
		    </tr>
		    <tr>
			<th>Статус:</th><td><?php echo $item->getStatus();?></td>
			<th>Номер объекта:</th><td><?php echo $item->getObject_Of_Investing(); ?></td>
			<th>Остаток:</th><td><?php echo number_format($item->getRemainder(), 2, '.', ' '); ?></td>
		    </tr>
		</tbody>
	    </table>
	    <br />
	    <?php endforeach;?>

	    <div class="clr"></div>
	</div>
    </div>
    <br />
    <br />
    <div class="clr"></div>
    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Платежи" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Платежи</cufontext></cufon>
	    </h2>
	    <table class="index" width="100%">
		<thead>
		    <tr>
			<th class="ta-center" width="60">Дата</th>
			<th class="ta-center" width="70">Договор</th>
			<th width="250">Описание</th>
			<th class="ta-center" width="90">Платеж</th>
			<th class="ta-center" width="90">Оплачено</th>
			<th class="ta-center" width="90">Остаток</th>
		    </tr>
		</thead>
		<tbody>
		<?php foreach ($payments as $item) :?>
	    
		<tr>
		    <td class="ta-center border"><?php echo date_format($item->getDate(), 'd/m/Y') ?></td>
		    <td class="ta-center border"><?php echo $item->getAgreement_No_(); ?></td>
		    <td class="border"><?php echo $item->getDescription() . ' (' . $item->getType() . ')'; ?></td>
		    <td class="ta-center border"><?php echo number_format($item->getPlan__Amount(), 2, '.', ' ');?></td>
		    <td class="ta-center border"><?php echo number_format($item->getPayed(), 2, '.', ' '); ?></td>
		    <td class="ta-center border"><?php echo number_format($item->getRemainder(), 2, '.', ' '); ?></td>
		</tr>
	    
		<?php endforeach;?>
		</tbody>
	    </table>
	    <br />
	    <div class="clr"></div>
	</div>
    </div>