<div class="block">
    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Договора" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Договора</cufontext></cufon>
	    </h2>

	    <div class="clr"></div>
	</div>
    </div>
    <br />
    <br />
    <div class="clr"></div>
    <div class="fbg">
	<div class="fbg_resize">
	    <h2>
		<cufon class="cufon cufon-canvas" alt="Платежи" style="width: 73px; height: 24px;"><canvas width="124" height="32" style="width: 124px; height: 32px; top: -5px; left: -16px;"></canvas><cufontext>Платежи</cufontext></cufon>
	    </h2>
		<div class="barpage">
		Страницы: 
		<a href="?act=gallery&id=71&page=1&lang=ua" id="active">1</a>
		<a href="?act=gallery&id=71&page=2&lang=ua">2</a>
		</div>
	    <div class="clr"></div>
	</div>
    </div>
</div>